# Generated by Django 2.2.5 on 2021-06-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='schoolid',
            field=models.CharField(choices=[('SMC Member', 'SMC Member'), ('grievance', 'grievance')], default='student', max_length=20),
        ),
    ]
