# Generated by Django 2.2.5 on 2021-06-20 02:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0003_auto_20210620_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_address', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=40)),
                ('template', models.FileField(upload_to='mail_app/mails')),
                ('send_on', models.DateTimeField(default=datetime.datetime(2021, 6, 20, 2, 41, 53, 711922, tzinfo=utc))),
                ('recipients_list', models.ManyToManyField(related_name='mail_list', to='GRsystem.MailRecipient')),
            ],
        ),
        migrations.CreateModel(
            name='MailAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_file', models.FileField(upload_to='')),
                ('attached_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='GRsystem.ScheduledMail')),
            ],
        ),
    ]
