# Generated by Django 2.2.5 on 2021-06-20 03:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0004_mailattachment_mailrecipient_scheduledmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmail',
            name='send_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 3, 12, 46, 246909, tzinfo=utc)),
        ),
    ]
